// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xrwqddyulbnaoyxijjmy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inhyd3FkZHl1bGJuYW95eGlqam15Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgzODQ4NDcsImV4cCI6MjA3Mzk2MDg0N30.NI7xabks6SMbNHZAXqPeLWKzRag4XysTscA5OMUbdtE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});